#!/bin/bash

# 🧪 Script de Teste do Sistema de Notificações Push
# Este script demonstra como testar o sistema de 3 níveis implementado

echo "🚀 TESTE DO SISTEMA DE NOTIFICAÇÕES PUSH - 3 NÍVEIS"
echo "=================================================="

# Configurações
API_BASE="http://localhost:8080/api"
CONTENT_TYPE="Content-Type: application/json"

echo ""
echo "📋 PRÉ-REQUISITOS:"
echo "1. ✅ Aplicação rodando em localhost:8080"
echo "2. ✅ Database com dados de usuários, organizações e contratos"
echo "3. ✅ Pelo menos 1 cliente com contrato titular"
echo "4. ✅ Pelo menos 1 motoboy com tokens push"

echo ""
echo "🔍 Verificando se aplicação está rodando..."
if curl -s "$API_BASE/actuator/health" > /dev/null; then
    echo "✅ Aplicação está online!"
else
    echo "❌ Aplicação não está rodando. Execute: ./gradlew bootRun"
    exit 1
fi

echo ""
echo "📝 EXEMPLO DE TESTE MANUAL:"
echo ""

echo "1️⃣ CRIAR NOVA DELIVERY (que ativará o sistema de notificação):"
echo ""
echo "curl -X POST '$API_BASE/deliveries' \\"
echo "  -H '$CONTENT_TYPE' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -d '{"
echo "    \"client\": {\"id\": \"CLIENT_UUID_HERE\"},"
echo "    \"fromAddress\": \"Rua das Flores, 123\","
echo "    \"fromLatitude\": -23.550520,"
echo "    \"fromLongitude\": -46.633308,"
echo "    \"toAddress\": \"Avenida Paulista, 456\","
echo "    \"toLatitude\": -23.561414,"
echo "    \"toLongitude\": -46.656219,"
echo "    \"recipientName\": \"João Silva\","
echo "    \"recipientPhone\": \"11999999999\","
echo "    \"totalAmount\": 50.00,"
echo "    \"itemDescription\": \"Documento importante\""
echo "  }'"

echo ""
echo "2️⃣ MONITORAR LOGS DA APLICAÇÃO:"
echo "Após criar a delivery, verifique os logs para ver o processo de notificação:"
echo ""
echo "LOGS ESPERADOS:"
echo "📄 Iniciando notificação de motoboys para delivery {id}"
echo "📄 Executando Nível 1: Organização titular para delivery {id}"
echo "📄 Notificação Nível 1 enviada para delivery {id}"
echo "📄 (ou após 2min) Executando Nível 2: Outras organizações..."
echo "📄 (ou após +2min) Executando Nível 3: Todos motoboys próximos..."

echo ""
echo "3️⃣ TESTAR TOKENS PUSH:"
echo ""
echo "# Registrar token de teste para motoboy"
echo "curl -X POST '$API_BASE/push/tokens' \\"
echo "  -H '$CONTENT_TYPE' \\"
echo "  -H 'Authorization: Bearer COURIER_JWT_TOKEN' \\"
echo "  -d '{"
echo "    \"token\": \"ExponentPushToken[FAKE_TOKEN_FOR_TESTING]\","
echo "    \"platform\": \"EXPO\","
echo "    \"deviceType\": \"MOBILE\""
echo "  }'"

echo ""
echo "# Enviar notificação de teste"
echo "curl -X POST '$API_BASE/push/test/{userId}' \\"
echo "  -H 'Authorization: Bearer ADMIN_JWT_TOKEN'"

echo ""
echo "🎯 RESULTADOS ESPERADOS:"
echo "================================"
echo ""
echo "✅ NÍVEL 1 (Organização Titular):"
echo "   - Busca motoboys da organização titular do cliente"
echo "   - Filtra apenas disponíveis e próximos (5km → 10km)"
echo "   - Envia notificações push"
echo "   - Se encontrar: PARA o processo"
echo "   - Se não encontrar: Aguarda 2min → Nível 2"
echo ""
echo "✅ NÍVEL 2 (Outras Organizações):"
echo "   - Busca motoboys de outras organizações do cliente"
echo "   - Aplica mesmo filtro geográfico"
echo "   - Se encontrar: PARA o processo"
echo "   - Se não encontrar: Aguarda 2min → Nível 3"
echo ""
echo "✅ NÍVEL 3 (Todos Próximos):"
echo "   - Busca TODOS motoboys disponíveis na área"
echo "   - Sem restrição de organização"
echo "   - Envia para todos encontrados"
echo "   - FIM do processo"

echo ""
echo "📊 MONITORAMENTO:"
echo "=================="
echo ""
echo "1. Logs da aplicação (nível INFO/DEBUG)"
echo "2. Status das deliveries no banco:"
echo "   SELECT id, status, created_at FROM deliveries ORDER BY created_at DESC LIMIT 5;"
echo ""
echo "3. Tokens push ativos:"
echo "   SELECT u.name, upt.platform, upt.is_active FROM user_push_tokens upt"
echo "   JOIN users u ON u.id = upt.user_id WHERE upt.is_active = true;"

echo ""
echo "🔧 CONFIGURAÇÕES IMPORTANTES:"
echo "=============================="
echo ""
echo "# application.properties"
echo "expo.access-token=\${EXPO_ACCESS_TOKEN:}"
echo "expo.push-url=\${EXPO_PUSH_URL:https://exp.host/--/api/v2/push/send}"
echo ""
echo "# Variáveis de ambiente para produção"
echo "export EXPO_ACCESS_TOKEN='your_real_expo_token'"

echo ""
echo "🎉 SISTEMA IMPLEMENTADO COM SUCESSO!"
echo "====================================="
echo ""
echo "O sistema de notificações push com 3 níveis está pronto!"
echo "Para testar completamente, execute o comando de criação de delivery acima"
echo "e monitore os logs da aplicação para ver o processo em ação."

echo ""
echo "📞 Para suporte: Verifique SISTEMA_NOTIFICACAO_PUSH_COMPLETO.md"